basePath: /
info:
  contact:
    name: Sean
  description: Simple swagger implementation in Go HTTP
  title: Go Rest API with Swagger for Level The Playing Field project
  version: "1.0"
paths: {}
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
